version: '3.4'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.server
    volumes:
      - ./models/model_checkpoints:/opt/app/model_checkpoints
    ports:
      - 8050:8050
    healthcheck:
      test: curl -v http://localhost:8050/
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 5s
    networks:
      - local

  test_client:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.tests
    depends_on:
      - server
    networks:
      - local
networks:
  local:
    driver: bridge