RELEVANT_COLUMNS = [
    "amount_tsh",
    "date_recorded",
    "funder",
    "gps_height",
    "installer",
    "longitude",
    "latitude",
    "num_private",
    "basin",
    "subvillage",
    "region_code",
    "district_code",
    "lga",
    "ward",
    "population",
    "public_meeting",
    "scheme_management",
    "permit",
    "construction_year",
    "extraction_type",
    "extraction_type_group",
    "extraction_type_class",
    "management",
    "management_group",
    "payment",
    "water_quality",
    "quantity",
    "source",
    "waterpoint_type",
    "status_group",
]

CATEGORICAL_COLLUMNS = [
    "funder",
    "installer",
    "basin",
    "subvillage",
    "lga",
    "ward",
    "public_meeting",
    "scheme_management",
    "permit",
    "extraction_type",
    "extraction_type_group",
    "extraction_type_class",
    "management",
    "management_group",
    "payment",
    "water_quality",
    "quantity",
    "source",
    "waterpoint_type",
]

ALL_FEATURE_COLS = [
    "id",
    "amount_tsh",
    "date_recorded",
    "funder",
    "gps_height",
    "installer",
    "longitude",
    "latitude",
    "wpt_name",
    "num_private",
    "basin",
    "subvillage",
    "region",
    "region_code",
    "district_code",
    "lga",
    "ward",
    "population",
    "public_meeting",
    "recorded_by",
    "scheme_management",
    "scheme_name",
    "permit",
    "construction_year",
    "extraction_type",
    "extraction_type_group",
    "extraction_type_class",
    "management",
    "management_group",
    "payment",
    "payment_type",
    "water_quality",
    "quality_group",
    "quantity",
    "quantity_group",
    "source",
    "source_type",
    "source_class",
    "waterpoint_type",
    "waterpoint_type_group",
]

LIGHTGBM_TRAINING_PARAMS = {
    "num_leaves": 60,
    "objective": "multiclass",
    "num_class": 3,
    "learning_rate": 0.03,
    "metric": "multi_logloss",
}

NUM_TRAINING_ROUNDS = 300
